// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: map_reduce.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MapReduceRequest_DataProvider int32

const (
	MapReduceRequest_raw   MapReduceRequest_DataProvider = 0
	MapReduceRequest_audio MapReduceRequest_DataProvider = 1
	MapReduceRequest_csv   MapReduceRequest_DataProvider = 2
)

// Enum value maps for MapReduceRequest_DataProvider.
var (
	MapReduceRequest_DataProvider_name = map[int32]string{
		0: "raw",
		1: "audio",
		2: "csv",
	}
	MapReduceRequest_DataProvider_value = map[string]int32{
		"raw":   0,
		"audio": 1,
		"csv":   2,
	}
)

func (x MapReduceRequest_DataProvider) Enum() *MapReduceRequest_DataProvider {
	p := new(MapReduceRequest_DataProvider)
	*p = x
	return p
}

func (x MapReduceRequest_DataProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapReduceRequest_DataProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_map_reduce_proto_enumTypes[0].Descriptor()
}

func (MapReduceRequest_DataProvider) Type() protoreflect.EnumType {
	return &file_map_reduce_proto_enumTypes[0]
}

func (x MapReduceRequest_DataProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapReduceRequest_DataProvider.Descriptor instead.
func (MapReduceRequest_DataProvider) EnumDescriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{1, 0}
}

type StatusResponse_ClientStatus int32

const (
	StatusResponse_idle            StatusResponse_ClientStatus = 0
	StatusResponse_working_mapper  StatusResponse_ClientStatus = 1
	StatusResponse_working_reducer StatusResponse_ClientStatus = 2
	StatusResponse_unknown         StatusResponse_ClientStatus = 3
)

// Enum value maps for StatusResponse_ClientStatus.
var (
	StatusResponse_ClientStatus_name = map[int32]string{
		0: "idle",
		1: "working_mapper",
		2: "working_reducer",
		3: "unknown",
	}
	StatusResponse_ClientStatus_value = map[string]int32{
		"idle":            0,
		"working_mapper":  1,
		"working_reducer": 2,
		"unknown":         3,
	}
)

func (x StatusResponse_ClientStatus) Enum() *StatusResponse_ClientStatus {
	p := new(StatusResponse_ClientStatus)
	*p = x
	return p
}

func (x StatusResponse_ClientStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusResponse_ClientStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_map_reduce_proto_enumTypes[1].Descriptor()
}

func (StatusResponse_ClientStatus) Type() protoreflect.EnumType {
	return &file_map_reduce_proto_enumTypes[1]
}

func (x StatusResponse_ClientStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusResponse_ClientStatus.Descriptor instead.
func (StatusResponse_ClientStatus) EnumDescriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{3, 0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{0}
}

type MapReduceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InputFile    string                        `protobuf:"bytes,1,opt,name=input_file,json=inputFile,proto3" json:"input_file,omitempty"`
	Script       string                        `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	DataProvider MapReduceRequest_DataProvider `protobuf:"varint,3,opt,name=data_provider,json=dataProvider,proto3,enum=MapReduceRequest_DataProvider" json:"data_provider,omitempty"`
	ReducerCount int64                         `protobuf:"varint,4,opt,name=reducer_count,json=reducerCount,proto3" json:"reducer_count,omitempty"`
}

func (x *MapReduceRequest) Reset() {
	*x = MapReduceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReduceRequest) ProtoMessage() {}

func (x *MapReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReduceRequest.ProtoReflect.Descriptor instead.
func (*MapReduceRequest) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{1}
}

func (x *MapReduceRequest) GetInputFile() string {
	if x != nil {
		return x.InputFile
	}
	return ""
}

func (x *MapReduceRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *MapReduceRequest) GetDataProvider() MapReduceRequest_DataProvider {
	if x != nil {
		return x.DataProvider
	}
	return MapReduceRequest_raw
}

func (x *MapReduceRequest) GetReducerCount() int64 {
	if x != nil {
		return x.ReducerCount
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{2}
}

func (x *CommonResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// status:
// 1: idle
// 2: working as mapper
// 3: working as reducer
// 4: unknown
type StatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status StatusResponse_ClientStatus `protobuf:"varint,1,opt,name=status,proto3,enum=StatusResponse_ClientStatus" json:"status,omitempty"`
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() StatusResponse_ClientStatus {
	if x != nil {
		return x.Status
	}
	return StatusResponse_idle
}

type MapPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  string `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	Second int64  `protobuf:"varint,2,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *MapPair) Reset() {
	*x = MapPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapPair) ProtoMessage() {}

func (x *MapPair) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapPair.ProtoReflect.Descriptor instead.
func (*MapPair) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{4}
}

func (x *MapPair) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *MapPair) GetSecond() int64 {
	if x != nil {
		return x.Second
	}
	return 0
}

type ReduceSliceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReduceId int64 `protobuf:"varint,1,opt,name=reduce_id,json=reduceId,proto3" json:"reduce_id,omitempty"`
}

func (x *ReduceSliceRequest) Reset() {
	*x = ReduceSliceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceSliceRequest) ProtoMessage() {}

func (x *ReduceSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceSliceRequest.ProtoReflect.Descriptor instead.
func (*ReduceSliceRequest) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{5}
}

func (x *ReduceSliceRequest) GetReduceId() int64 {
	if x != nil {
		return x.ReduceId
	}
	return 0
}

type ReduceSliceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*MapPair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *ReduceSliceResponse) Reset() {
	*x = ReduceSliceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceSliceResponse) ProtoMessage() {}

func (x *ReduceSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceSliceResponse.ProtoReflect.Descriptor instead.
func (*ReduceSliceResponse) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{6}
}

func (x *ReduceSliceResponse) GetPairs() []*MapPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type JobDoneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResultPath string `protobuf:"bytes,2,opt,name=result_path,json=resultPath,proto3" json:"result_path,omitempty"`
}

func (x *JobDoneRequest) Reset() {
	*x = JobDoneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDoneRequest) ProtoMessage() {}

func (x *JobDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDoneRequest.ProtoReflect.Descriptor instead.
func (*JobDoneRequest) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{7}
}

func (x *JobDoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobDoneRequest) GetResultPath() string {
	if x != nil {
		return x.ResultPath
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId       string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientEndpoint string `protobuf:"bytes,2,opt,name=client_endpoint,json=clientEndpoint,proto3" json:"client_endpoint,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_map_reduce_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_map_reduce_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_map_reduce_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RegisterRequest) GetClientEndpoint() string {
	if x != nil {
		return x.ClientEndpoint
	}
	return ""
}

var File_map_reduce_proto protoreflect.FileDescriptor

var file_map_reduce_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6d, 0x61, 0x70, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xe0, 0x01, 0x0a, 0x10,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x12, 0x43, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x61, 0x5f,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e,
	0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x0c,
	0x64, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x2b, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x07, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x63, 0x73, 0x76, 0x10, 0x02, 0x22, 0x32,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x96, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4e, 0x0a, 0x0c, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x69,
	0x64, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x6d, 0x61, 0x70, 0x70, 0x65, 0x72, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x77, 0x6f, 0x72,
	0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x72, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x03, 0x22, 0x37, 0x0a, 0x07, 0x4d,
	0x61, 0x70, 0x50, 0x61, 0x69, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x53, 0x6c,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x13, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x4d, 0x61, 0x70, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x22, 0x41,
	0x0a, 0x0e, 0x4a, 0x6f, 0x62, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x22, 0x57, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x32, 0xd3, 0x01, 0x0a, 0x0e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a,
	0x03, 0x6d, 0x61, 0x70, 0x12, 0x11, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x12, 0x11, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0f, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x10, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x5f, 0x73, 0x6c,
	0x69, 0x63, 0x65, 0x12, 0x13, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63,
	0x65, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x32, 0xa4, 0x01, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x64, 0x6f, 0x6e, 0x65, 0x12,
	0x0f, 0x2e, 0x4a, 0x6f, 0x62, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x0b, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x5f, 0x64, 0x6f,
	0x6e, 0x65, 0x12, 0x0f, 0x2e, 0x4a, 0x6f, 0x62, 0x44, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x10, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x77, 0x68, 0x61, 0x74, 0x62, 0x6f,
	0x79, 0x2f, 0x6d, 0x61, 0x70, 0x5f, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_map_reduce_proto_rawDescOnce sync.Once
	file_map_reduce_proto_rawDescData = file_map_reduce_proto_rawDesc
)

func file_map_reduce_proto_rawDescGZIP() []byte {
	file_map_reduce_proto_rawDescOnce.Do(func() {
		file_map_reduce_proto_rawDescData = protoimpl.X.CompressGZIP(file_map_reduce_proto_rawDescData)
	})
	return file_map_reduce_proto_rawDescData
}

var file_map_reduce_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_map_reduce_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_map_reduce_proto_goTypes = []interface{}{
	(MapReduceRequest_DataProvider)(0), // 0: MapReduceRequest.DataProvider
	(StatusResponse_ClientStatus)(0),   // 1: StatusResponse.ClientStatus
	(*Empty)(nil),                      // 2: Empty
	(*MapReduceRequest)(nil),           // 3: MapReduceRequest
	(*CommonResponse)(nil),             // 4: CommonResponse
	(*StatusResponse)(nil),             // 5: StatusResponse
	(*MapPair)(nil),                    // 6: MapPair
	(*ReduceSliceRequest)(nil),         // 7: ReduceSliceRequest
	(*ReduceSliceResponse)(nil),        // 8: ReduceSliceResponse
	(*JobDoneRequest)(nil),             // 9: JobDoneRequest
	(*RegisterRequest)(nil),            // 10: RegisterRequest
}
var file_map_reduce_proto_depIdxs = []int32{
	0,  // 0: MapReduceRequest.data_provider:type_name -> MapReduceRequest.DataProvider
	1,  // 1: StatusResponse.status:type_name -> StatusResponse.ClientStatus
	6,  // 2: ReduceSliceResponse.pairs:type_name -> MapPair
	3,  // 3: Client_Service.map:input_type -> MapReduceRequest
	3,  // 4: Client_Service.reduce:input_type -> MapReduceRequest
	2,  // 5: Client_Service.status:input_type -> Empty
	7,  // 6: Client_Service.get_reduce_slice:input_type -> ReduceSliceRequest
	9,  // 7: Server_Service.map_done:input_type -> JobDoneRequest
	9,  // 8: Server_Service.reduce_done:input_type -> JobDoneRequest
	10, // 9: Server_Service.register:input_type -> RegisterRequest
	4,  // 10: Client_Service.map:output_type -> CommonResponse
	4,  // 11: Client_Service.reduce:output_type -> CommonResponse
	5,  // 12: Client_Service.status:output_type -> StatusResponse
	8,  // 13: Client_Service.get_reduce_slice:output_type -> ReduceSliceResponse
	4,  // 14: Server_Service.map_done:output_type -> CommonResponse
	4,  // 15: Server_Service.reduce_done:output_type -> CommonResponse
	4,  // 16: Server_Service.register:output_type -> CommonResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_map_reduce_proto_init() }
func file_map_reduce_proto_init() {
	if File_map_reduce_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_map_reduce_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapReduceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceSliceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceSliceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobDoneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_map_reduce_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_map_reduce_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_map_reduce_proto_goTypes,
		DependencyIndexes: file_map_reduce_proto_depIdxs,
		EnumInfos:         file_map_reduce_proto_enumTypes,
		MessageInfos:      file_map_reduce_proto_msgTypes,
	}.Build()
	File_map_reduce_proto = out.File
	file_map_reduce_proto_rawDesc = nil
	file_map_reduce_proto_goTypes = nil
	file_map_reduce_proto_depIdxs = nil
}
